{
 "title": "DerProzess - Kafka",
 "tags": [ "kafka" ],
 "time": { "from": "2019-02-27T13:45:00.778Z", "to": "2019-02-27T13:48:34.659Z" },
 "templating": {
  "list": [
   {
    "name": "test",
    "query": "show tag values from cpu with key = \"test\""
   }
  ]
 },
 "panels": [
  {
   "title": "Under replicated partitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |). Alert if value is greater than 0.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kafka_server_replica_manager",
     "select": [
      [
       { "params": [ "UnderReplicatedPartitions" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "singlestat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable. Alert if value is greater than 0.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Offline Partitions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kafka_controller_kafka_controller",
     "select": [
      [
       { "params": [ "OfflinePartitionsCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Active controller",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster. Alert if the aggregated sum across all brokers in the cluster is anything other than 1 because there should be exactly one controller per cluster.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kafka_controller_kafka_controller",
     "select": [
      [
       { "params": [ "ActiveControllerCount" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Partition count / host",
   "type": "graph",
   "description": "Number of partitions on this broker. This should be mostly even across all brokers.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Partition count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_server_replica_manager",
     "select": [
      [
       { "params": [ "PartitionCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Broker CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "user cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "broker" }
     ]
    },
    {
     "alias": "system cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "broker" }
     ]
    },
    {
     "alias": "iowait cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "broker" }
     ]
    }
   ]
  },
  {
   "title": "Clients CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "user cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "driver" }
     ]
    },
    {
     "alias": "system cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "driver" }
     ]
    },
    {
     "alias": "iowait cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "driver" }
     ]
    }
   ]
  },
  {
   "title": "MB/s sent to Kafka",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "drivers",
     "select": [
      [
       { "params": [ "sizeOfMessage" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Producer latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "drivers",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/$test$/" }
     ]
    }
   ]
  },
  {
   "title": "network per broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "brokers bytes in/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpExtInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "broker" }
     ]
    },
    {
     "alias": "brokers bytes out/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpExtOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "broker" }
     ]
    }
   ]
  },
  {
   "title": "network per client",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "clients bytes in/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpExtInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "driver" }
     ]
    },
    {
     "alias": "clients bytes out/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpExtOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "driver" }
     ]
    }
   ]
  },
  {
   "title": "Bytes / sec",
   "type": "graph",
   "description": "Aggregate incoming / outgoing byte rate.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Bytes In / sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_server_broker_topic_metrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "BytesInPerSec" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Bytes Out / sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_server_broker_topic_metrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "BytesOutPerSec" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests / sec",
   "type": "graph",
   "description": "Request rate.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Produce req Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT percentile(\"MeanRate\", 95) FROM \"kafka_network_request_metrics\" WHERE (\"request\" = 'Produce' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "99thPercentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "Produce" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Fetch Consumer req Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT percentile(\"MeanRate\", 95) FROM \"kafka_network_request_metrics\" WHERE (\"request\" = 'FetchConsumer' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "99thPercentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "FetchConsumer" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Fetch Follower req Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT percentile(\"MeanRate\", 95) FROM \"kafka_network_request_metrics\" WHERE (\"request\" = 'FetchFollower' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "99thPercentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "FetchFollower" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Messages In / sec",
   "type": "graph",
   "description": "Aggregate incoming message rate.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Messages In /s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_server_broker_topic_metrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "MessagesInPerSec" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Fetch and Produce Req / sec",
   "type": "graph",
   "description": "Fetch and Produce requests total time",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Produce Requests / sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kafka_server_broker_topic_metrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "TotalProduceRequestsPerSec" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Fetch Requests / sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kafka_server_broker_topic_metrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "TotalFetchRequestsPerSec" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Failed Production and Fetch req / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Max failed Produce req / sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_server_broker_topic_metrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "FailedProduceRequestsPerSec" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Max failed Fetch req / sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_server_broker_topic_metrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "FailedFetchRequestsPerSec" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Leader Election",
   "type": "graph",
   "description": "Leader election count",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Leader election Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_controller_controller_stats",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "LeaderElectionRateAndTimeMs" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Unclean Leader election Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_controller_controller_stats",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "UncleanLeaderElectionsPerSec" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Leader election latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "jolokia_agent_url" ], "type": "tag" }
     ],
     "measurement": "kafka_controller_controller_stats",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "graph",
   "description": "Maximum lag in messages between the follower and leader replicas",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Max Replica Lag $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_server_replica_fetcher_manager",
     "select": [
      [
       { "params": [ "MaxLag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clientId", "operator": "=", "value": "Replica" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Request handler Idle %",
   "type": "graph",
   "description": "Average fraction of time the request handler threads are idle",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Idle % ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_server_kafka_request_handler_pool",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "RequestHandlerAvgIdlePercent" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Network processor avg Idle %",
   "type": "graph",
   "description": "Average fraction of time the network processor threads are idle",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Network processor avg Idle % ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_socket_server",
     "select": [
      [
       { "params": [ "NetworkProcessorAvgIdlePercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Request / Response queue size",
   "type": "graph",
   "description": "Size of the request queue. A congested request queue will not be able to process incoming or outgoing requests",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Request Queue size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_channel_per_processor",
     "select": [
      [
       { "params": [ "RequestQueueSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Response Queue size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_channel_per_processor",
     "select": [
      [
       { "params": [ "ResponseQueueSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Produce/FetchConsumer/FetchFollower Total time",
   "type": "graph",
   "description": "Total time in ms to serve the specified request",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Produce req total time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "Produce" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "TotalTimeMs" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Consumer fetch req total time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "FetchConsumer" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "TotalTimeMs" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Follower fetch req total time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "FetchFollower" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "TotalTimeMs" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Log flush time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_log_log_flush_stats",
     "select": [
      [
       { "params": [ "Max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "LogFlushRateAndTimeMs" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Kafka Produce Requests processing time",
   "type": "graph",
   "description": "Queue: Time the request waits in the request queue\nLocal: Time the request is processed at the leader\nRemote: Time the request waits for the follower. This is non-zero for produce requests when acks=all\nResponse queue: Time the request waits in the response queue\nResponse send: Time to send the response",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Request queue time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT last(\"OneMinuteRate\") FROM \"kafka_network_request_metrics\" WHERE (\"name\" = 'RequestQueueTimeMs' AND \"request\" = 'Produce') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "RequestQueueTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "Produce" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Request local time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT last(\"OneMinuteRate\") FROM \"kafka_network_request_metrics\" WHERE (\"name\" = 'LocalTimeMs' AND \"request\" = 'Produce') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "LocalTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "Produce" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Request remote time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT last(\"OneMinuteRate\") FROM \"kafka_network_request_metrics\" WHERE (\"name\" = 'LocalTimeMs' AND \"request\" = 'Produce') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "RemoteTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "Produce" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Request response queue time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT last(\"OneMinuteRate\") FROM \"kafka_network_request_metrics\" WHERE (\"name\" = 'RemoteTimeMs' AND \"request\" = 'Produce') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ResponseQueueTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "Produce" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Request response send time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT last(\"OneMinuteRate\") FROM \"kafka_network_request_metrics\" WHERE (\"name\" = 'RemoteTimeMs' AND \"request\" = 'Produce') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ResponseSendTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "Produce" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Kafka Fetch Consumer Requests processing time",
   "type": "graph",
   "description": "Queue: Time the request waits in the request queue\nLocal: Time the request is processed at the leader\nRemote: Time the request waits for the follower. This is non-zero for produce requests when acks=all\nResponse queue: Time the request waits in the response queue\nResponse send: Time to send the response",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Request queue time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "RequestQueueTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "FetchConsumer" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Request local time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT last(\"OneMinuteRate\") FROM \"kafka_network_request_metrics\" WHERE (\"name\" = 'LocalTimeMs' AND \"request\" = 'Produce') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "LocalTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "FetchConsumer" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Request remote time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT last(\"OneMinuteRate\") FROM \"kafka_network_request_metrics\" WHERE (\"name\" = 'LocalTimeMs' AND \"request\" = 'Produce') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "RemoteTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "FetchConsumer" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Request response queue time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT last(\"OneMinuteRate\") FROM \"kafka_network_request_metrics\" WHERE (\"name\" = 'RemoteTimeMs' AND \"request\" = 'Produce') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ResponseQueueTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "FetchConsumer" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Request response send time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT last(\"OneMinuteRate\") FROM \"kafka_network_request_metrics\" WHERE (\"name\" = 'RemoteTimeMs' AND \"request\" = 'Produce') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ResponseSendTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "FetchConsumer" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Kafka Fetch Follower Requests processing time",
   "type": "graph",
   "description": "Queue: Time the request waits in the request queue\nLocal: Time the request is processed at the leader\nRemote: Time the request waits for the follower. This is non-zero for produce requests when acks=all\nResponse queue: Time the request waits in the response queue\nResponse send: Time to send the response",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Request queue time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "RequestQueueTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "FetchFollower" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Request local time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT last(\"OneMinuteRate\") FROM \"kafka_network_request_metrics\" WHERE (\"name\" = 'LocalTimeMs' AND \"request\" = 'Produce') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "LocalTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "FetchFollower" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Request remote time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT last(\"OneMinuteRate\") FROM \"kafka_network_request_metrics\" WHERE (\"name\" = 'LocalTimeMs' AND \"request\" = 'Produce') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "RemoteTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "FetchFollower" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Request response queue time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT last(\"OneMinuteRate\") FROM \"kafka_network_request_metrics\" WHERE (\"name\" = 'RemoteTimeMs' AND \"request\" = 'Produce') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ResponseQueueTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "FetchFollower" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Request response send time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_network_request_metrics",
     "query": "SELECT last(\"OneMinuteRate\") FROM \"kafka_network_request_metrics\" WHERE (\"name\" = 'RemoteTimeMs' AND \"request\" = 'Produce') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ResponseSendTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "FetchFollower" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Isr Shrink / Expand per seconds",
   "type": "graph",
   "description": "IsrShrinksPerSec : If a broker goes down, ISR for some of the partitions will shrink. When that broker is up again, ISR will be expanded once the replicas are fully caught up. Other than that, the expected value for both ISR shrink rate and expansion rate is 0.\n\nIsrExpandsPerSec : When a broker is brought up after a failure, it starts catching up by reading from the leader. Once it is caught up, it gets added back to the ISR.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_server_replica_manager",
     "select": [
      [
       { "params": [ "IsrShrinksPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_server_replica_manager",
     "select": [
      [
       { "params": [ "IsrExpandsPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  },
  {
   "title": "Fetch / Produce purgatory size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Produce",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_server_delayed_operation_purgatory",
     "select": [
      [
       { "params": [ "PurgatorySize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "delayedOperation", "operator": "=", "value": "Produce" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    },
    {
     "alias": "Fetch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kafka_server_delayed_operation_purgatory",
     "select": [
      [
       { "params": [ "PurgatorySize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "delayedOperation", "operator": "=", "value": "Fetch" },
      { "condition": "AND", "key": "test", "operator": "=~", "value": "/^$test$/" }
     ]
    }
   ]
  }
 ]
}